# Generated by Django 5.0 on 2024-01-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raise_request',
            name='customer_mobile_number',
            field=models.IntegerField(default=1234567890),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raise_request',
            name='customer_name',
            field=models.CharField(default='Santhosh', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raise_request',
            name='request_title',
            field=models.CharField(default='Pc not turning on', max_length=20),
            preserve_default=False,
        ),
    ]
