# Generated by Django 5.0 on 2024-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_raise_request_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request',
            name='customer_mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
