# Generated by Django 5.0 on 2024-01-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_alter_raise_request_customer_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raise_request',
            old_name='request_title',
            new_name='service_you_need',
        ),
        migrations.AddField(
            model_name='raise_request',
            name='details_of_it',
            field=models.TextField(default='PC not turning on'),
            preserve_default=False,
        ),
    ]
