# Generated by Django 5.0 on 2024-01-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_rename_request_title_raise_request_service_you_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request',
            name='details_of_it',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
